---
parameters:
  - name: pool
    type: string
    default: "Auto-Scaling-Agents-Linux"

jobs:
  - job: Gitleaks
    displayName: "🔑 Gitleaks Scanner"
    pool:
      name: ${{ parameters.pool }}
    steps:
      - checkout: self
      - checkout: EMEA-GI-AzDO-pipeline-modules
      - template: ../steps/gitleaks.yaml
...
